name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change si ta branche principale a un autre nom

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  deploy:
    name: Deploy to Vercel
    needs: test  # Attend que les tests réussissent avant de déployer
    runs-on: ubuntu-latest
    if: success()  # Ne se lance que si les tests passent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
